-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 09:20:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotellerio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotellerio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotellerio` DEFAULT CHARACTER SET utf8 ;
USE `hotellerio` ;

-- -----------------------------------------------------
-- Table `hotellerio`.`admin_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`admin_auth` (
  `username_01` VARCHAR(50) NOT NULL,
  `password_01` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`breakfast_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`breakfast_menu` (
  `id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `item_type` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`customer_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`customer_details` (
  `cust_name` VARCHAR(50) NOT NULL,
  `cust_age` INT(11) NOT NULL,
  `cust_address` VARCHAR(100) NOT NULL,
  `cust_phone` DOUBLE NOT NULL,
  `Guest_no` INT(11) NULL DEFAULT NULL,
  `entry_time` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2) ON UPDATE CURRENT_TIMESTAMP(2),
  `cust_Id` INT(11) NOT NULL,
  PRIMARY KEY (`cust_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`employee_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`employee_details` (
  `ID` INT(11) NOT NULL,
  `name_n` VARCHAR(75) NOT NULL,
  `age` INT(11) NOT NULL,
  `address_n` VARCHAR(200) NOT NULL,
  `phone_n` DOUBLE NOT NULL,
  `username_n` VARCHAR(75) NOT NULL,
  `password_n` VARCHAR(50) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`employee_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`employee_login` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`laundry_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`laundry_menu` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`lunch_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`lunch_menu` (
  `id1` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`lunch_non_veg_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`lunch_non_veg_menu` (
  `id2` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id2`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_breakfast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_breakfast` (
  `cust_id` INT(11) NOT NULL,
  `name_of_item` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `total_price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_dinner_non_veg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_dinner_non_veg` (
  `cust_id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_dinner_veg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_dinner_veg` (
  `cust_id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_laundry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_laundry` (
  `cust_id` INT(11) NOT NULL,
  `cloth_name` VARCHAR(45) NOT NULL,
  `total_pieces` INT(11) NOT NULL,
  `total_price` FLOAT NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_lunch_non_veg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_lunch_non_veg` (
  `cust_id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_lunch_veg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_lunch_veg` (
  `cust_id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `total_price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`order_snacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`order_snacks` (
  `cust_id` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NULL DEFAULT NULL,
  `no_of_plates` INT(11) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`room_availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`room_availability` (
  `id` INT(11) NOT NULL,
  `SIngle` INT(11) NULL DEFAULT NULL,
  `DOuuble` INT(11) NULL DEFAULT NULL,
  `DOuplex` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`room_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`room_details` (
  `cust_ID` INT(11) NOT NULL,
  `single` INT(11) NULL DEFAULT NULL,
  `cost_s` INT(11) NULL DEFAULT NULL,
  `double` INT(11) NULL DEFAULT NULL,
  `cost_db` INT(11) NULL DEFAULT NULL,
  `douplex` INT(11) NULL DEFAULT NULL,
  `cost_dp` INT(11) NULL DEFAULT NULL,
  `date` TIMESTAMP(2) NULL DEFAULT NULL,
  PRIMARY KEY (`cust_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`room_rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`room_rent` (
  `ID` INT(11) NOT NULL,
  `single` INT(11) NOT NULL,
  `douuble` INT(11) NOT NULL,
  `douplex` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`snacks_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`snacks_menu` (
  `id3` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id3`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`transport_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`transport_cost` (
  `id` INT(11) NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hotellerio`.`transport_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotellerio`.`transport_table` (
  `cust_Id` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `car_no` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
