/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vishnu Vardhan CH
 */
public class Hotellerio extends javax.swing.JFrame {

    /**
     * Creates new form Hotellerio
     */
    public Hotellerio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Customer_dettails = new javax.swing.JButton();
        check_availabillity = new javax.swing.JButton();
        room_alloccate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME TO HOTELLERIO....");

        Customer_dettails.setText("New Enroll");
        Customer_dettails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_dettailsActionPerformed(evt);
            }
        });

        check_availabillity.setText("Check Availability");
        check_availabillity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_availabillityActionPerformed(evt);
            }
        });

        room_alloccate.setText("Allocate Room");
        room_alloccate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_alloccateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(room_alloccate)
                    .addComponent(check_availabillity)
                    .addComponent(Customer_dettails)
                    .addComponent(jLabel1))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(Customer_dettails)
                .addGap(35, 35, 35)
                .addComponent(check_availabillity)
                .addGap(36, 36, 36)
                .addComponent(room_alloccate)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_availabillityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_availabillityActionPerformed
try  {
           // DBConnect dbc = new DBConnect();
           int SIngle=0,DOuuble=0,TRiple=0,DOuplex=0;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/for_hotellerio";
            String user = "root";
            String pass = "1.414magiC";
            Connection con = DriverManager.getConnection(url,user,pass);
            String sql = " select * from room_availability";
            PreparedStatement ps=con.prepareStatement(sql);
			ResultSet rs=ps.executeQuery();
                        while(rs.next()){
                            //String cust_name = rs.getString(1) ;
                             SIngle =  rs.getInt(2);
                             DOuuble = rs.getInt(3);
                             TRiple = rs.getInt(4);
                             DOuplex = rs.getInt(5);
                        }
JOptionPane.showMessageDialog(null,"rooms available are "+SIngle+" single rooms, "+DOuuble+" double rooms, "+TRiple+" triple rooms, "+DOuplex+" douplex rooms","Display Message", JOptionPane.INFORMATION_MESSAGE);

            //System.out.println(SIngle+" "+DOuuble+" "+TRiple+" "+DOuplex);
            con.close();
//            int single2= Integer.valueOf(siNGle.getText());
//            int douuble2=Integer.valueOf(doUUble.getText());
//            int triple2=Integer.valueOf(trIPle.getText());
//            int douplex2=Integer.valueOf(doUPlex.getText());
//            int a = SIngle-single2;
//            int b= DOuuble-douuble2;
//            int c= TRiple-triple2;
//            int d=DOuplex-douplex2;
//            if(a<=0 || b<=0 || c<=0 || d<=0)
//            {
//                JOptionPane.showMessageDialog(null,"Oops!!Your requested rooms cannot be booked as there are "+a+" single rooms, "+b+" double rooms, "+c+" triple rooms, "+d+" douplex rooms left!!","Display message", JOptionPane.INFORMATION_MESSAGE);
//            }else{
//                JOptionPane.showMessageDialog(null,"rooms left after booking will be "+a+" single rooms, "+b+" double rooms, "+c+" triple rooms, "+d+" douplex rooms","Display Message", JOptionPane.INFORMATION_MESSAGE);
//            }
            
        } 
        catch (ClassNotFoundException | SQLException e) {
            System.out.println("no result found "+e);
        }        // TODO add your handling code here:
                                  







//new check_Availability().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_check_availabillityActionPerformed

    private void Customer_dettailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_dettailsActionPerformed
            new customer_Details().setVisible(true);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_dettailsActionPerformed

    private void room_alloccateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_alloccateActionPerformed
            new room_Allocate().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_room_alloccateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotellerio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotellerio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotellerio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotellerio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotellerio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customer_dettails;
    private javax.swing.JButton check_availabillity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton room_alloccate;
    // End of variables declaration//GEN-END:variables
}
