/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Vishnu Vardhan CH
 */
public class New_Employee extends javax.swing.JFrame {

    /**
     * Creates new form New_Employee
     */
    public New_Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        admit_n = new javax.swing.JButton();
        reset_05 = new javax.swing.JButton();
        cancel_05 = new javax.swing.JButton();
        password_n = new javax.swing.JPasswordField();
        conf_passwrd_n = new javax.swing.JPasswordField();
        name_n = new javax.swing.JTextField();
        age_n = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_n = new javax.swing.JTextArea();
        phone_num_n = new javax.swing.JTextField();
        username_n = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Address");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel7.setText("Confirm Password");

        jLabel8.setText("New Employee Entry !!");

        admit_n.setText("Admit");
        admit_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admit_nActionPerformed(evt);
            }
        });

        reset_05.setText("Reset");
        reset_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_05ActionPerformed(evt);
            }
        });

        cancel_05.setText("Cancel");
        cancel_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_05ActionPerformed(evt);
            }
        });

        password_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_nActionPerformed(evt);
            }
        });

        conf_passwrd_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_passwrd_nActionPerformed(evt);
            }
        });

        address_n.setColumns(20);
        address_n.setRows(5);
        jScrollPane1.setViewportView(address_n);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset_05)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admit_n))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(name_n, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(age_n, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(username_n, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(phone_num_n, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(password_n, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(conf_passwrd_n, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(age_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(phone_num_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(username_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(password_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(conf_passwrd_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admit_n)
                    .addComponent(reset_05)
                    .addComponent(cancel_05))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_nActionPerformed

    private void conf_passwrd_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_passwrd_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_passwrd_nActionPerformed

    private void cancel_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_05ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancel_05ActionPerformed

    private void reset_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_05ActionPerformed
        // TODO add your handling code here:
        name_n.setText("");
        age_n.setText("");
        address_n.setText("");
        phone_num_n.setText("");
        username_n.setText("");
        password_n.setText("");
        conf_passwrd_n.setText("");
    }//GEN-LAST:event_reset_05ActionPerformed

    private void admit_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admit_nActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.YES_NO_OPTION;
        int y = JOptionPane.showConfirmDialog(this, "Your Message", "Title on Box", x);
        if(y == 0) 
        {
        //System.out.println("Yes option");
try{
    Random rn=new Random();
    int rnn = rn.nextInt(1000000);
                      Class.forName("com.mysql.jdbc.Driver");
                        String url="jdbc:mysql://localhost:3306/hotellerio";
			String user="root";
			String pass="1.414magiC";
	               Connection conn =DriverManager.getConnection(url,user,pass);
                         String sql="insert into employee_details values(?,?,?,?,?,?,?)";
                       PreparedStatement pst=conn.prepareStatement(sql);
                       pst.setInt(1,rnn);
			pst.setString(2, String.valueOf(name_n.getText()));
                        pst.setInt(3,Integer.valueOf(age_n.getText()));
                        pst.setString(4,String.valueOf(address_n.getText()));
                        pst.setDouble(5,Double.valueOf(phone_num_n.getText()));
                        pst.setString(6,String.valueOf(username_n.getText()));
			pst.setString(7, String.valueOf(password_n.getPassword()));
                        pst.executeUpdate(sql);
                        conn.close();
           }
       catch(Exception e) {
           System.out.println(e);
                      }        } 
        else {
         //New_Employee ap = new New_Employee();
         //ap.setVisible(true);
         
        }       
    }//GEN-LAST:event_admit_nActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address_n;
    private javax.swing.JButton admit_n;
    private javax.swing.JTextField age_n;
    private javax.swing.JButton cancel_05;
    private javax.swing.JPasswordField conf_passwrd_n;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_n;
    private javax.swing.JPasswordField password_n;
    private javax.swing.JTextField phone_num_n;
    private javax.swing.JButton reset_05;
    private javax.swing.JTextField username_n;
    // End of variables declaration//GEN-END:variables
}
